# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AI(object):
    def setupUi(self, AI):
        AI.setObjectName("AI")
        AI.resize(1120, 910)
        self.centralwidget = QtWidgets.QWidget(AI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, 5, 1101, 851))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\SUVRODIP\\Downloads\\wallpaper\\ai-loader-opt.gif"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 20, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setAcceptDrops(False)
        self.pushButton.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";\n"
"color: rgb(255, 11, 64);")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 20, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setAcceptDrops(False)
        self.pushButton_2.setStyleSheet("font: 18pt \"Arial Rounded MT Bold\";\n"
"color: rgb(53, 229, 0);")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 770, 211, 71))
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textBrowser.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 227, 15);\n"
"border-radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(880, 770, 211, 71))
        self.textBrowser_2.setStyleSheet("background-color: transparent;\n"
"border-radius:none;\n"
"color: rgb(255, 227, 15);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        AI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        AI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AI)
        self.statusbar.setObjectName("statusbar")
        AI.setStatusBar(self.statusbar)

        self.retranslateUi(AI)
        QtCore.QMetaObject.connectSlotsByName(AI)

    def retranslateUi(self, AI):
        _translate = QtCore.QCoreApplication.translate
        AI.setWindowTitle(_translate("AI", "AI"))
        self.pushButton.setText(_translate("AI", "STOP"))
        self.pushButton_2.setText(_translate("AI", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AI = QtWidgets.QMainWindow()
    ui = Ui_AI()
    ui.setupUi(AI)
    AI.show()
    sys.exit(app.exec_())
